[package]
name = "phmcom-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["cargo"] }
dotenv = "0.15"

[[bin]]
name = "phmcom-cli"
path = "src/main.rs"
