[package]
name = "phmcom-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["cargo"] }
dotenv = "0.15"
env_logger = "0.11.5"
log = "0.4.22"
tokio = { version = "1.39.2", features = ["full"] }

[[bin]]
name = "phmcom-cli"
path = "src/main.rs"
