#!/bin/bash

set -e

SCRIPT_DIR="$(dirname $0)"
PROJECT_ROOT="$(readlink -f "$SCRIPT_DIR/../..")"

PACKAGES_TO_CHECK="
    sdbx-main \
    sdbx-commons \
"

OLD_PWD="$PWD"

finish() {
    cd "$OLD_PWD"
}

trap finish EXIT

cd "$PROJECT_ROOT"

printf "\n\n--== Build Environment ==--\n\n"
rustc \
    --version
cargo \
    --version

printf "\n\n--== Check Code Style ==--\n\n"
cargo fmt \
    --all \
    -- \
        --check

for PACKAGE in $PACKAGES_TO_CHECK; do
    cd "$PROJECT_ROOT/$PACKAGE"

    printf "\n\n--== Run Linter for $PACKAGE ==--\n\n"
    cargo clippy \
        --all-features \
        -- \
            --deny "warnings"

    printf "\n\n--== Check Doc for $PACKAGE ==--\n\n"
    RUSTDOCFLAGS="-Dwarnings" \
    cargo doc \
        --no-deps \
        --all-features \
        --document-private-items
document
